name: Update Homebrew Formula

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          fetch-depth: 0

      - name: Get release info
        id: release
        run: |
          echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "tarball_url=https://github.com/${{ github.repository }}/archive/refs/tags/${GITHUB_REF#refs/tags/}.tar.gz" >> $GITHUB_OUTPUT

      - name: Calculate SHA256
        id: sha
        run: |
          curl -L ${{ steps.release.outputs.tarball_url }} -o morama.tar.gz
          echo "sha256=$(shasum -a 256 morama.tar.gz | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      - name: Update Formula
        run: |
          sed -i "s|url \".*\"|url \"${{ steps.release.outputs.tarball_url }}\"|" Formula/morama.rb
          sed -i "s|sha256 \".*\"|sha256 \"${{ steps.sha.outputs.sha256 }}\"|" Formula/morama.rb
          sed -i "s|version \".*\"|version \"${{ steps.release.outputs.tag_name }}\"|" Formula/morama.rb

      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Formula/morama.rb
          if ! git diff --quiet || ! git diff --staged --quiet; then
            git commit -m "Update morama to ${{ steps.release.outputs.tag_name }}"
            git push origin main
          fi 
